/// <reference path="angularjs/angular.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
/// <reference path="lodash/lodash.d.ts" />
/// <reference path="angular-ui-router/angular-ui-router.d.ts" />
/// <reference path="angular-material/angular-material.d.ts" />
/// <reference path="core-js/core-js.d.ts" />
/// <reference path="async/async.d.ts" />
/// <reference path="../../pip-webui-nav/dist/pip-webui-nav.d.ts"/>
/// <reference path="../../pip-webui-layouts/dist/pip-webui-layouts.d.ts"/>
/// <reference path="../../pip-webui-services/dist/pip-webui-services.d.ts"/>
